run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - errcheck
      text: ".*defer.*"

linters-settings:
  golint:
    min-confidence: 0.8
